on: [pull_request]

jobs:
  wait-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.3.2
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: "poetry"
      - name: Install dependencies
        run: poetry install
      - name: Wait test profiling
        run: poetry run python scripts/performance_test/wait_test.py
